#!/usr/bin/perl -w

=head1 NAME

dh_eosapp - deprecated helper

=cut

use strict;

=head1 SYNOPSIS

B<dh_eosapp> [S<I<debhelper options>>]

=head1 DESCRIPTION

B<dh_eosapp> was a debhelper program that moved installed files from the
typical /usr prefix to the application specific /endless/app prefix. The
functionality has been moved into B<dh_installdeb>.

=cut

1;

=head1 SEE ALSO

L<debhelper(7)>

This program is a part of debhelper.

=head1 AUTHOR

Dan Nicholson <nicholson@endlessm.com>

=cut
